---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-employee
  name: sb-employee-external
  namespace: default
spec:
  ports:
  - nodePort: 32318
    port: 8092
    protocol: TCP
    targetPort: 8092
  selector:
    app: sb-employee
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-native-employee
  name: sb-native-employee-external
  namespace: default
spec:
  ports:
    - nodePort: 32600
      port: 8092
      protocol: TCP
      targetPort: 8092
  selector:
    app: sb-native-employee
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qk-jvm-employee
  name: qk-jvm-employee-external
  namespace: default
spec:
  ports:
  - nodePort: 31450
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: qk-jvm-employee
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qk-native-employee
  name: qk-native-employee-external
  namespace: default
spec:
  ports:
  - nodePort: 31524
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: qk-native-employee
  sessionAffinity: None
  type: NodePort
