apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curling-jvm-qk
  name: curling-jvm-qk
spec:
  containers:
  - args:
    - sh
    - -c
    - while(true) do echo "requesting..."; wget -T5 -O- http://qk-jvm-employee:8081/hello ; sleep 0.2; done
    image: busybox
    name: curling-jvm-qk
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
