apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curling-native-qk
  name: curling-native-qk
spec:
  containers:
  - args:
    - sh
    - -c
    - while(true) do echo "requesting..."; wget -T1 -O- http://qk-native-employee:8080/hello ; sleep 1.2; done
    image: busybox
    name: curling-native-qk
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
