apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qk-jvm-employee
  name: qk-jvm-employee
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: qk-jvm-employee
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qk-jvm-employee
    spec:
      containers:
      - image: docker.io/library/quarkus-employee-jvm:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: quarkusemployee
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        ports:
          - containerPort: 8080
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
