apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-qk-deploy
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-qk-deploy
  sessionAffinity: None
  type: ClusterIP
