apiVersion: v1
kind: Service
metadata:
  labels:
    app: qk-jvm-employee
  name: qk-jvm-employee
  namespace: default
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: qk-jvm-employee
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
