apiVersion: v1
kind: Service
metadata:
  labels:
    app: qk-native-employee
  name: qk-native-employee
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: qk-native-employee
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
