apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-native-employee
  name: sb-native-employee
  namespace: default
spec:
  ports:
  - port: 8093
    protocol: TCP
    targetPort: 8092
  selector:
    app: sb-native-employee
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
