apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qk-native-employee
  name: qk-native-employee
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: qk-native-employee
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qk-native-employee
    spec:
      containers:
      - image: quarkus-employee-native:0.0.2-SNAPSHOT-scratch
        imagePullPolicy: IfNotPresent
        name: quarkusemployee
        ports:
         - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
        resources:
          limits:
            memory: 1.5G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
