apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sb-employee
  name: sb-employee
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sb-employee
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sb-employee
    spec:
      containers:
      - image: employee-sb:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: employeespringboot
        readinessProbe:
          tcpSocket:
            port: 8092
          initialDelaySeconds: 1
          periodSeconds: 1
        ports:
          - containerPort: 8092
        resources:
          limits:
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
