apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sb-native-employee
  name: sb-native-employee
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-native-employee
  template:
    metadata:
      labels:
        app: sb-native-employee
    spec:
      containers:
      - image: sb-employee-native:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: sb-native-employee
        readinessProbe:
          tcpSocket:
            port: 8092
          initialDelaySeconds: 1
          periodSeconds: 1
        ports:
          - containerPort: 8092
        resources:
          limits:
            memory: 500Mi
      restartPolicy: Always
